title: Yoga Sree Durga K
logo: /assets/img/logo.png
description: Im a Release Manager with 8 years of experience in IT Service Management
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
