title: Yoga Sree Durga K
logo: /assets/img/logo.png
description: Im a Release manager new to Machine Learning, with my expertise in Service Delivery. I have extensive experience in SOX audits and other internal/external audits
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
